version: '3'

services:
  web_player_server_dev:
    image : yashsisodia/wplayer_server_dev:1
    
    ports:
      - 8890:8890
    volumes:      
      - ..:/app/
      - ~/.gitconfig:/root/.gitconfig
      - /tmp/.X11-unix:/tmp/.X11-unix     
    environment:      
      DISPLAY:
      XAUTHORITY:
      ASPNETCORE_URLS: http://0.0.0.0:8890,https://0.0.0.0:8890 

    networks:
      - wplayerServer_network    
    container_name: wplayerServer
    command: sleep infinity
    
  
networks:
  wplayerServer_network:
    driver: bridge
