FROM streamer_build_base AS compile

RUN mkdir /app
COPY . /app

RUN mkdir /app/build
RUN cd /app/build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake && make -j 4

FROM ubuntu:20.04 AS release

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    libavformat58 libavcodec58 libswresample3 libswscale5 libavutil56 libavdevice58 libavfilter7 libpostproc55 \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir /home/app 
COPY --from=compile /app/build/streamer/streamer /app/
WORKDIR /app

EXPOSE 8181
CMD ["./streamer", "-s", "1"]