FROM ubuntu:18.04 as base

RUN apt-get update && apt-get install -y --no-install-recommends build-essential ca-certificates curl unzip wget git pkg-config \
    libavformat-dev libavcodec-dev libswresample-dev libswscale-dev libavutil-dev libavdevice-dev libavfilter-dev libpostproc-dev \
    --fix-missing && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/Kitware/CMake/releases/download/v3.19.0-rc1/cmake-3.19.0-rc1-Linux-x86_64.sh \
    && chmod +x cmake-3.19.0-rc1-Linux-x86_64.sh \
    && ./cmake-3.19.0-rc1-Linux-x86_64.sh --prefix=/usr/local --skip-license \
    && rm cmake-3.19.0-rc1-Linux-x86_64.sh

RUN git clone https://github.com/microsoft/vcpkg.git && cd vcpkg && ./bootstrap-vcpkg.sh 
RUN cd vcpkg && ./vcpkg install boost-filesystem boost-regex boost-system boost-thread boost-dll poco websocketpp cpr jsoncpp cryptopp fmt spdlog zlib openssl