version: '3'

services:
  web_player_full_linux20_dev:
    image: streamer_build_base:latest

    network_mode: host  # Use host networking for WebRTC UDP connectivity

    volumes:
      - ..:/webwork/
      - ~/.gitconfig:/root/.gitconfig
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY:
      XAUTHORITY:

    container_name: wplayer_linux20
    command: sleep infinity
