name: C++ CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies for Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends build-essential ca-certificates curl unzip wget git pkg-config \
            libavformat-dev libavcodec-dev libswresample-dev libswscale-dev libavutil-dev libavdevice-dev libavfilter-dev libpostproc-dev \
            --fix-missing

        # Download and install vcpkg
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh

        # Install dependencies with vcpkg
        ./vcpkg install boost-filesystem boost-regex boost-system boost-thread boost-dll poco websocketpp cpr jsoncpp cryptopp fmt spdlog zlib openssl

    - name: Cache vcpkg
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/cache@v2
      with:
        path: vcpkg
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg/installed') }}

    - name: Install dependencies for Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        # Download and install vcpkg
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        bootstrap-vcpkg.bat
        vcpkg integrate install

        # Install dependencies with vcpkg
        vcpkg install boost-filesystem boost-regex boost-system boost-thread boost-dll poco websocketpp cpr jsoncpp cryptopp fmt spdlog zlib openssl

    - name: Set up environment
      shell: bash
      run: |
        if [ -d "vcpkg" ]; then
          export VCPKG_ROOT=$PWD/vcpkg
        fi
    - name: Configure and build
      run: |
        ls
        cd streamer
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
        make -j 4

    - name: Print binaries
      run: |
        ls